[project]
name = "hydromt_SFINCS_v3"
version = "0.1.0"
description = "HydroMT + SFINCS environment"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
# core
python = "*"
pip = "*"



# typical stack
# requests = "*"
# aiohttp = "*"
xarray = "*"
numpy = "*"
pandas = "*"
# scipy = "*"
rasterio = "*"
geopandas = "*"
pyproj = "*"
shapely = "*"
matplotlib-base = "*"
dask-core = "*"
netcdf4 = "*"
# fsspec = "*"
pyyaml = "*"
cartopy= "*"
hydromt_sfincs ="*"

# jupyter
jupyterlab = "*"
ipykernel = "*"

# Define the default environment
[environments]
default = { solve-group = "default" }

# Tasks for kernel registration
[tasks]
# Automatically setup kernel after install
postinstall = "setup-kernel"

# Register the hydromt_sfincs kernel with user's Jupyter
setup-kernel = "python -m ipykernel install --user --name hydromt_sfincs2 --display-name 'hydromt_sfincs (pixi)'"

# Start JupyterLab
notebook = "jupyter lab"

# List installed kernels
list-kernels = "jupyter kernelspec list"

# Remove the hydromt_sfincs kernel
clean-kernel = "jupyter kernelspec remove -f hydromt_sfincs || echo 'Kernel not found'"