
[model]
type = "geom"
risk = false

[model.srs]
value = "EPSG:4326"

[output]
path = "output/juba_flood_event"

[output.csv]
name1 = "output.csv"

[output.geom]
name1 = "spatial.gpkg"

[hazard]
file = "data/hazard/Pokuantra_T50_BL.nc"
elevation_reference = "DEM"

[hazard.settings]
srs = "EPSG:4326"

[exposure.geom]
file1 = "data/exposure/buildings.gpkg"

[exposure.geom.settings]
srs = "EPSG:4326"

[vulnerability]
file = "data/vulnerability/vulnerability_curves.csv"
step_size = 0.01
