[project]
name = "ibf_hydro_model"
version = "0.1.0"
description = "HydroMT + wflow workshop environment"
authors = ["Jerom Aerts <jeromaerts@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
install-wflow = r'julia --color=yes -e "ENV[\"JULIA_SSL_CA_ROOTS_PATH\"]=\"\"; using Pkg; Pkg.add(url=\"https://github.com/Deltares/Wflow.jl\", subdir=\"Wflow\")"'
install-julia = "powershell -ExecutionPolicy Bypass -File install_julia.ps1"
lab = "jupyter lab"

[dependencies]
python = ">=3.10,<3.12"
pip = "*"

# DO NOT put hydromt here to avoid conda pinning 1.2.0

# typical stack
requests = "*"
aiohttp = "*"
xarray = "*"
numpy = "*"
pandas = "*"
scipy = "*"
rasterio = "*"
geopandas = "*"
pyproj = "*"
shapely = "*"
matplotlib-base = "*"
dask-core = "*"
netcdf4 = "*"
fsspec = "*"
pyyaml = "*"
cartopy= "*"

# jupyter
jupyterlab = "*"
ipykernel = "*"

[pypi-dependencies]
hydromt = "==1.3.0rc5"
hydromt-wflow = { git = "https://github.com/Deltares/hydromt_wflow.git" }
