[project]
name = "ibf_hydro_model"
version = "0.1.0"
description = "HydroMT + wflow workshop environment"
authors = ["Jerom Aerts <jeromaerts@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = ">=3.10,<3.12"
pip = "*"

# DO NOT put hydromt here to avoid conda pinning 1.2.0

# typical stack
requests = "*"
aiohttp = "*"
xarray = "*"
numpy = "*"
pandas = "*"
scipy = "*"
rasterio = "*"
geopandas = "*"
pyproj = "*"
shapely = "*"
matplotlib-base = "*"
dask-core = "*"
netcdf4 = "*"
fsspec = "*"
pyyaml = "*"
cartopy= "*"

# jupyter
jupyterlab = "*"
ipykernel = "*"

[pypi-dependencies]
hydromt = "==1.3.0rc5"
hydromt-wflow = { git = "https://github.com/Deltares/hydromt_wflow.git" }

[tasks]
# Automatically setup kernel after install
postinstall = "setup-kernel"

# Register the hydromt_sfincs kernel with user's Jupyter
setup-kernel = "python -m ipykernel install --user --name hydrological --display-name 'IBF hydromt Wflow (pixi)'"
notebook = "jupyter lab"